
#二、本文除了介绍多环境配置，这里顺便介绍外部配置的常见使用方法。

#1.可使用约定配置/自定义配置  其中约定配置可根据IDE智能提示
server:
  port: 9001 #生产环境端口


#2.配置随机值
author:
 my-id1: ${random.int} #生成随机整数
 my-id2: ${random.int(10)}
 my-id3: ${random.int[10,20]}
 my-id4: ${random.long}
 my-name: ${random.value} #生成随机字符串
 my-uuid: ${random.uuid} #生成UUID


#3.使用命令行参数进行环境配置

# 使用命令：$ java -jar xxx.jar --server.port=8088  该优先级高于普通数据源;
# 禁用命令：springApplication.setAddCommandLineProperties(false) 启动前关闭即可;

#4.支持占位符
app:
 info:
  uri: http://localhost:${server.port}

#5. @ConfigurationProperties("xx.xx")

# 松绑定  1.驼峰(xxXx) 2.虚线(xx-xx) 3.下划线(xx_xx) 4.环境变量(XX_XX_XX) 均能映射到JAVA的驼峰
my:
 favorite:
  websites:
    - https://docs.spring.io/spring-boot/docs/current/reference/html
    - https://springcloud.cc/spring-cloud-dalston.html
    - https://github.com/yizhiwazi
